name: Run Script

on:
    push:
        branches: [master]
    workflow_dispatch: {}

jobs:
    script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 
            - name: Give Permission to Script 
              run: chmod +x ./Assignment/run.sh 
            - name: Running Script
              run: bash ./Assignment/run.sh
# Add this file in .github folder because it can't be run 
