name: Assignment 2 - Matrix Testing & Conditional Build

on:
  push:
    branches: [main]             # run tests + build on main
    tags: ["v*.*.*"]             # also run build when version tag is pushed
  pull_request:                   # always run tests for PRs
  workflow_dispatch:              # allow manual trigger

jobs:
  test:
    name: Run Tests (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          mkdir -p test-results
          npm test | tee test-results/results-node-${{ matrix.node }}.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

  build:
    name: Build Project
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build --if-present || echo "No build script found"
          mkdir -p dist
          echo "Dummy Build File" > dist/build.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
