name: Assignment 2 - Matrix Testing & Conditional Build

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: Run tests and save results
        run: |
          mkdir -p test-results
          npm test --if-present | tee test-results/results-node-${{ matrix.node }}.txt
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node }}
          path: test-results/

  summarize_tests:
    name: Summarize Test Results
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download all test artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-results
          merge-multiple: true
      - name: Combine results
        run: |
          cat test-results/results-node-*.txt > all-tests-summary.txt
          cat all-tests-summary.txt
      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: all-test-summary
          path: all-tests-summary.txt

  build:
    name: Build Project
    needs: [summarize_tests]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Build project
        run: |
          mkdir -p dist
          echo "Dummy Build File" > dist/output.txt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
