name: Source - Trigger Demo

# When to run the workflow
on:
    push:
        branches: [master]
    pull_request:
        branches: [main]
    workflow_dispatch : {}

jobs:
    print-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Print trigger details
            # Event: which triggered the workflow (push, pull_request, workflow_dispatch)
            # Ref: the branch or tag )  ref/heads/main, refs/pull/12/merge , etc
            # SHA: commit ID
            # Actor: Github username who trigger the workflow. 
              run: |
                echo "Event: ${{ github.event_name }}"  
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
