name: Run Script

on:
    push:
        branches: [master]
    workflow_dispatch: {}

jobs:
    script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 
            - name: Run Shell Script 
              run: chmod +x ./Assignment/run.sh 
